### ISSUE TITLE
textTinyR fails to install on Mac, El Capitan v 10.11.6

### ISSUE THREAD

**Issue by elcovi** [mlampros/textTinyR#3] opened 2017-01-12 03:00 UTC
Hi,

I'm having problems trying to install textTinyR. I've installed Brew and executed "brew install boost" to install libraries (boost-1.63.0 already installed), but i still keep getting an error, see below [output]. 

I'm using:

El Capitan v 10.11.6
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
RStudio Version 1.0.136 – © 2009-2016 RStudio, Inc.

I have updated all my R-studio packages, also, I have installed Rcpp, RcppArmadillo, and BH libraries. 

I greatly appreciate some help.
Thanks,
Ignacio

[output] --------------------------------------------------------

install.packages("textTinyR")
Package which is only available in source form, and may need compilation
  of C/C++/Fortran: ‘textTinyR’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘textTinyR’

trying URL 'https://cran.rstudio.com/src/contrib/textTinyR_1.0.1.tar.gz'
Content type 'application/x-gzip' length 610316 bytes (596 KB)
==================================================
downloaded 596 KB

* installing *source* package ‘textTinyR’ ...
** package ‘textTinyR’ successfully unpacked and MD5 sums checked
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether clang++ supports C++11 features by default... no
checking whether clang++ supports C++11 features with -std=c++11... yes
checking for pkg-config... no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking boost/locale.hpp usability... yes
checking boost/locale.hpp presence... yes
checking for boost/locale.hpp... yes
checking for main in -lboost_locale... no
configure: error: Unable to find the boost-locale. In DEBIAN/UBUNTU: sudo apt-get install libboost-all-dev; sudo apt-get install libboost-locale-dev, FEDORA : yum install boost-devel,
					OSX/brew : brew install boost
ERROR: configuration failed for package ‘textTinyR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/textTinyR’
Warning in install.packages :
  installation of package ‘textTinyR’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/wh/mx3hyttx77b551_kjsgyk3_h0000gn/T/RtmpmcrgTt/downloaded_packages’
--------------------------------------------------

**Comment by mlampros** [comment] 2017-01-12 14:22
I'm sorry for the late reply,

the package [check results](https://cran.r-project.org/web/checks/check_results_textTinyR.html) show that the package can't be installed on both versions of the Mac OS. Temporarily I can fix the issue on the 1st version of the Mac OS ( r-devel-macos-x86_64-clang -- macOS 10.12 (Sierra) -- Apple LLVM version 8.0.0; gfortran 6.1.0 ), but unfortunately there are no error output messages for the 2nd version ( r-release-osx-x86_64-mavericks -- OS X 10.9.2 (13C64) -- Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn), gfortran 4.8.2 ). The [check results of the 2nd version](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64-mavericks/textTinyR-00install.html) are similar to your issue indicating that either the boost-locale are not installed or the boost library is installed in the wrong directory / path. 
<br>
From a search on the web I found a [second way](http://stackoverflow.com/questions/104322/how-do-you-install-boost-on-macos) to install the boost library using **sudo port install boost**, which probably installs the boost library in a different directory as homebrew . However I work mainly on a Linux OS and I would recommend a new installation, if you can uninstall the previous boost installation in a secure way.
<br>
What you can test in first place is if your current boost installation works in R (without using the BH library). Can you copy-paste  the following code chunk in an RStudio-C++ file using : File > New File > C++ File , then save the file with your name of preference and click *Source* to compile,

```R
# include <RcppArmadillo.h>
// [[Rcpp::depends("RcppArmadillo")]]
// [[Rcpp::plugins(cpp11)]]

#include <boost/algorithm/string.hpp>
#include <boost/range/algorithm_ext/erase.hpp>

// [[Rcpp::export]]
std::string example(std::string word, std::string any_character = "123<>?.") {

  boost::remove_erase_if(word, boost::is_any_of(any_character));
  
  return word;
}

```
<br>

If I run,

<br>

```R
example("example123")

```

on a Linux OS with boost == 1.55.0 I receive,

```R

"example"            # the numbers are removed

```

Please tell me if that works (in first place).

**Comment by elcovi** [comment] 2017-01-12 15:39
Thank you, for your prompt reply.
I'll definitely try your recommendations, and I'll let you know.

Thanks, again.
Ignacio



From:  Lampros Mouselimis <notifications@github.com>
Reply-To:  mlampros/textTinyR
<reply+009c7c41433f780c48723baadcbac7da9e11d3cb52a6c4b192cf00000001148f53319
2a169ce0befd3dc@reply.github.com>
Date:  Thursday, January 12, 2017 at 9:22 AM
To:  mlampros/textTinyR <textTinyR@noreply.github.com>
Cc:  ILC <2coviella@gmail.com>, Author <author@noreply.github.com>
Subject:  Re: [mlampros/textTinyR] textTinyR fails to install on Mac, El
Capitan v 10.11.6 (#3)

**Comment by mlampros** [comment] 2017-01-21 11:20
I close this issue, as detailed installation instructions for the *Macintosh OSx* were added in the *README* file.

**Closed by mlampros** 2017-01-21 11:20 UTC

**Comment by elcovi** [comment] 2017-02-10 01:02
Hi,
Sorry it has taken me so long to reply (it's been crazy!). 

I have tried everything. Uninstalled boost (brew),  reinstalled it; then installed it through the MacPorts link you provided, etc., and still could not install the textTinyR package.

I tried running the code you provided, and it runs fine, only, when i take out these three lines:

# include <RcppArmadillo.h>
// [[Rcpp::depends("RcppArmadillo")]]
// [[Rcpp::plugins(cpp11)]]

I think there's some problems with RcppArmadillo (even though i reinstalled from scratch).

Any thoughts would be greatly appreciated (no rush).

Thanks,
Ignacio

**Comment by mlampros** [comment] 2017-02-10 12:56
Hello,

the [package check results](https://cran.r-project.org/web/checks/check_results_textTinyR.html) show that textTinyR can be installed on a [MAC OS 10.12 (Sierra)](https://www.r-project.org/nosvn/R.check/r-devel-macos-x86_64-clang/textTinyR-00check.html) but not on a [MAC OS X 10.9.2 (Mavericks)](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64-mavericks/textTinyR-00install.html).
I took me a while (too) to figure out how to install the package on MAC OS sierra, but the problem is that I do not have access to a computer with El Capitan installed. If you already have uninstalled Rcpp and RcppArmadillo and re-installed them (from within an R-session) then the last think to check would be if your current clang version supports c++11 features. From those three lines try to exclude the 
```R
// [[Rcpp::plugins(cpp11)]]
```
and re-run the code chunk to see if this is the issue.

**Comment by elcovi** [comment] 2017-02-10 16:14
Hi,
Ok, so i partially solve the problem of running the script you sent. I had to reinstall and link the 'gfortran' and 'gcc' binaries (new versions). Now, i can compile it and run it exactly as you had it.

I still can't install 'textTinyR' in my system with El Capitan, though. I get the same error as before: "error: Unable to find the boost-locale."

I'll continue exploring. Thanks for all your help.

**Comment by mlampros** [comment] 2017-02-10 17:36
I think you have done what is possible and I'm sorry that I can't solve the issue for this version of Macintosh.  The last think to do is to go to the [main page](https://github.com/mlampros/textTinyR) of the textTinyR package and click on **clone or download** to download the package locally in ZIP format, then extract the zip file and from the **src** folder open the **export_all_funcs.cpp** file in an Rstudio session. The *export_all_funcs.cpp* includes all the Rcpp functions which should/can be exported in an R-session. Then click on *source* to observe if this file compiles locally without the use of the configuration file, which is not necessary in this case (Probably you will also have to create an *.R/Makevars* file in your home directory).
first test this and let me know

**Comment by elcovi** [comment] 2017-02-10 17:41
Definitely. I'll work on it, and I'll let you know.

Thanks for all your input.


From:  Lampros Mouselimis <notifications@github.com>
Reply-To:  mlampros/textTinyR
<reply+009c7c41b2c6ef8610fc8fb98126446254f65f3af7e184d792cf0000000114b5bc3b9
2a169ce0befd3dc@reply.github.com>
Date:  Friday, February 10, 2017 at 12:36 PM
To:  mlampros/textTinyR <textTinyR@noreply.github.com>
Cc:  ILC <2coviella@gmail.com>, Author <author@noreply.github.com>
Subject:  Re: [mlampros/textTinyR] textTinyR fails to install on Mac, El
Capitan v 10.11.6 (#3)
